### PR TITLE
Changing plane color

### PR DESCRIPTION
**Pull request by fabiodinatale**
This *PR* was opened in order to update the file `Plane.urdf` in the folder `lib/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane/FlatPlane`, adding the possibility to change its color.

### CODE REVIEW

**Comment by fabiodinatale** [comment]
The aim of this *PR* is to change the color of the plane displayed in the iDynTree Visualizer.

After performing the modification (i.e. including the `<color>` tag and inserting the proper RGBA values), using the command `idyntree-model-view`, the plane was shown with the desired color.
Despite this and despite the installation procedure was properly followed, the plane and the robot had still the same color when the visualizer is opened through a simulation.

This problem was related to these lines of code of the `iDynTreeIrrlichtVisualizer.m` file:
```m
obj.viz.enviroment().addLight('sun1');
obj.viz.enviroment().lightViz('sun1').setType(iDynTree.DIRECTIONAL_LIGHT);
obj.viz.enviroment().lightViz('sun1').setDirection(iDynTree.Direction(-1, 0, 0));
obj.viz.enviroment().addLight('sun2');
obj.viz.enviroment().lightViz('sun2').setType(iDynTree.DIRECTIONAL_LIGHT);
obj.viz.enviroment().lightViz('sun2').setDirection(iDynTree.Direction(1, 0, 0));
```
which set the lights of the environment.
Commenting them out, it was possible to display both the robot and the plane with their real colors.

Using the **_Blame_** function of *GitHub*, it was possible to discover that these lines where added through [this commit](https://github.com/ami-iit/matlab-whole-body-simulator/commit/3fca8c3154407843a435f6b9f4b1387bc16aaad7) by @Giulero, to whom we ask: *are these lines important for some specific reason and thus they **can't** be commented or is it possible to comment them?*

Thanks in advance for your response!

**Comment by Giulero** [comment]
Ciao @fabiodinatale ! Yes, these lines just set the light. You can happily remove them :)

**Comment by fabiodinatale** [comment]
Thanks for the very quick feedback @Giulero! Going to comment them then! 😄

**Comment by fabiodinatale** [comment]
Friendly ping @VenusPasandi for the Review!
Thanks!

**Review by VenusPasandi — APPROVED** [review]

**Comment by traversaro** [comment]
@VenusPasandi can we merge? Thanks!

**Comment by fabiodinatale** [comment]
> can we merge? Thanks!

Done!

**Pull request merged**
