### PR TITLE
Modify visualizer

### PR DESCRIPTION
**Pull request by fabiodinatale**
This *PR* introduce some modifications in the following scripts:
* `iDynTreIrrlichtVisualizer.m`;
* `Utils.m`.
in order to let the Visualizer display a plane (flat or inclined).

Closes https://github.com/ami-iit/matlab-whole-body-simulator/issues/77.

### CODE REVIEW

**Comment by fabiodinatale** [comment]
After some checks on the code because of errors appearing during the compilation phase, it is now possible to review the Pull Request.

**Comment by VenusPasandi** [comment]
Hi @fabiodinatale,

I added some commits to the PR. Basically, my commits include:

- Adding the urdf of the plane to the repo
- Simplify the plane urdf to only one plane
- remove the duplication of the function "compute rotation matrix of the contact surface"
- make the visualizer compatible with its previous version, so if someone is using the visualizer, his/her code works fine also after merging this PR.
- Edit the function "compute rotation matrix of the contact surface" to include also the "if condition".

About the function "compute rotation matrix of the contact surface", it seems that the error that we saw was actually because of the length of the function, so if we reduce the comment part in the function, the error is solved.

With the new commits, you should be able to run a simulation in a horizontal/inclined surface. Please check if you could use it in your local project.

**Comment by fabiodinatale** [comment]
Hi @VenusPasandi, thanks for your review and the modifications you made to the code.
In order to check that everything works also on another machine, the latest version of this branch was downloaded and installed. Everything went fine, but when running the simulation, the plane is not displayed in the Visualizer, as the `urdf` file is not present in the folder `robotology-superbuild/build/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane/FlatPlane`, even if the same file is available in the corresponding source directory.
The file was manually copied and it is possible to confirm that with your modifications the plane is displayed with the proper inclination.

**Comment by traversaro** [comment]
> About the problem explained above, we tried to reduce the length of the path, but this solution did not solve the problem.
> Could the format of the file be the cause of this problem? @traversaro

How did you installed the new branch? If you switched to the new branch and run `make install` without first re-running CMake it is possible that CMake is not aware that a new file is there. If you run `cmake` the problem should be fixed.

**Comment by VenusPasandi** [comment]
> > About the problem explained above, we tried to reduce the length of the path, but this solution did not solve the problem.
> > Could the format of the file be the cause of this problem? @traversaro
> 
> How did you installed the new branch? If you switched to the new branch and run `make install` without first re-running CMake it is possible that CMake is not aware that a new file is there. If you run `cmake` the problem should be fixed.

Yes, I first run `cmake` and then `make install`, it creates the new folders but it does not create the new file. @traversaro please note that we located the urdf file in +mwbs/+Visualizer/+robotVisualizer/Urdf/Plane/FlatPlane where we have all the matlab files. I think when we install the repo, it creates all the matlab files in mex folder, and the urdf file is not a matlab file, so it does not locate it in mex folder. It is just my feeling, I don't know if it is correct.

**Comment by traversaro** [comment]
Ok, let me check.

**Comment by fabiodinatale** [comment]
> Yes, I first run cmake and then make install, it creates the new folders but it does not create the new file.

Just to confirm that I followed the same procedure and had the same results.

**Comment by traversaro** [comment]
Indeed, I just tried and the files installed are:
~~~
traversaro@IITICUBLAP257:~/robotology-superbuild/buildapt/src/matlab-whole-body-simulator$ make install
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_robotSensors_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/slblocks.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_visualizers_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/skew.m
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/Utils.m
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/computeRotationMatrixFromNormal.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/Rp2H.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/H2Rp.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/exponentialMap.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/rollPitchYawFromRotation.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane/FlatPlane
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/iDynTreeIrrlichtVisualizer.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/RobotVisualizer.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/initRobotVisualizer.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+robotDynWC
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+robotDynWC/step_block.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+robotDynWC/step_block_with_closed_chain.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/loadRobotDynamicsWithContactsCB.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/initRobotDynamicsWithContactsCB.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/initRobotDynamicsWithContactsCB_closedChains.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+iDynTree2WBTmappers
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+iDynTree2WBTmappers/loadReducedModel.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+iDynTree2WBTmappers/KinDynComputations.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/init_mask_RobotDynWithContactsClosedChainCB.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_unilateral_linear_impact.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_free_acceleration.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_J_and_JDot_nu_split_points.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_contact_wrench_in_sole_frames.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/prepare_optimization_matrix.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/get_feet_contact_state.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/prepare_foot_print.m
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/Contacts.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_free_contact_acceleration.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_velocity.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_J_and_JDot_nu_in_contact_frames.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_contact_points.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_unilateral_linear_contact.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_damped_psudo_inverse.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@State
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@State/State.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Robot
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Robot/Robot.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/getModelPathFromFileNameAndYarpFinder.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotSensors
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotSensors/+IMUsensor
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotSensors/+IMUsensor/IMUsensorProc.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_robotDynamicsWithContacts_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/meshes
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/meshes/hokuyo.dae
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/meshes/hokuyo.stl
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/robots
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/robots/RRbot1
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/robots/RRbot1/model.urdf
~~~
so `+robotVisualizer/Urdf/Plane/FlatPlane/Plane.urdf` is not installed. So, I checked why these files should be installed in the first place, and this is in the `CMakeLists.txt`: 
~~~
# Copy the classes and Simulink slx library files
install(
  DIRECTORY ${M_FILES_DIR}
  DESTINATION ${MATLAB_WHOLE_BODY_SIMULATOR_INSTALL_MATLAB_FILESDIR}
  USE_SOURCE_PERMISSIONS
  FILES_MATCHING
  PATTERN "*.m"
  PATTERN "*.slx")
~~~
from https://github.com/ami-iit/matlab-whole-body-simulator/blob/c760c0d80337d0128704b4124607f8739a9e3000/CMakeLists.txt#L25 . Probably the problem is that there the parameters:
~~~
  FILES_MATCHING
  PATTERN "*.m"
  PATTERN "*.slx"
~~~
only install `.m` and `.slx` files. Removing those parameters, I obtain:
~~~
traversaro@IITICUBLAP257:~/robotology-superbuild/buildapt/src/matlab-whole-body-simulator$ make install
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_robotSensors_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/slblocks.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_visualizers_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/skew.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/Utils.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/computeRotationMatrixFromNormal.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/Rp2H.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/H2Rp.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/exponentialMap.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Utils/rollPitchYawFromRotation.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane/FlatPlane
-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane/FlatPlane/Plane.urdf
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/iDynTreeIrrlichtVisualizer.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/RobotVisualizer.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/initRobotVisualizer.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+robotDynWC
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+robotDynWC/step_block.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+robotDynWC/step_block_with_closed_chain.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/loadRobotDynamicsWithContactsCB.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/initRobotDynamicsWithContactsCB.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/initRobotDynamicsWithContactsCB_closedChains.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+iDynTree2WBTmappers
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+iDynTree2WBTmappers/loadReducedModel.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/+iDynTree2WBTmappers/KinDynComputations.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotDynamicsWithContacts/init_mask_RobotDynWithContactsClosedChainCB.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_unilateral_linear_impact.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_free_acceleration.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_J_and_JDot_nu_split_points.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_contact_wrench_in_sole_frames.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/prepare_optimization_matrix.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/get_feet_contact_state.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/prepare_foot_print.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/Contacts.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_free_contact_acceleration.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_velocity.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_J_and_JDot_nu_in_contact_frames.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_contact_points.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_unilateral_linear_contact.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Contacts/compute_damped_psudo_inverse.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@State
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@State/State.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Robot
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/@Robot/Robot.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/getModelPathFromFileNameAndYarpFinder.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotSensors
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotSensors/+IMUsensor
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+RobotSensors/+IMUsensor/IMUsensorProc.m
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/mex/mwbs_robotDynamicsWithContacts_lib.slx
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/meshes
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/meshes/hokuyo.dae
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/meshes/hokuyo.stl
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/robots
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/robots/RRbot1
-- Up-to-date: /home/traversaro/robotology-superbuild/buildapt/install/share/RRbot/robots/RRbot1/model.urdf
~~~

So you can see that `-- Installing: /home/traversaro/robotology-superbuild/buildapt/install/mex/+mwbs/+Visualizers/+robotVisualizer/Urdf/Plane/FlatPlane/Plane.urdf` is correctly installed.
As I do not see any advantage in having those parameters (just more problems like this the next time somebody wants to add a file with a different extension), I just dropped them in the next commit.

**Comment by traversaro** [comment]
Problem with the installation fixed in https://github.com/ami-iit/matlab-whole-body-simulator/pull/79/commits/61f8d797a1fc2601f57b7ffe37d3659a01b9a956 .

**Review by traversaro — APPROVED** [review]

**Comment by fabiodinatale** [comment]
Confirm that the modification done by @traversaro solved the problem:
image
Thanks!

**Comment by VenusPasandi** [comment]
Thanks @traversaro for the detailed explanation about the problem.

**Review by VenusPasandi — APPROVED** [review]

**Pull request merged**
